version: '3'
services:
    postgres:
        image: postgres:17
        container_name: finance-app-postgres
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: root
            POSTGRES_DB: finance-app
        ports:
            - '5434:5432'
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
